# Write your MySQL query statement below

# THIS SELECT STATMENT CHANGES ONLY THE VIEW
# I TRIED USING UPDATE SET, BUT IT DID NOT WORK!!
SELECT user_id, 
CONCAT(UPPER(SUBSTRING(name, 1, 1)) , LOWER(SUBSTRING(name, 2))) AS name 
FROM Users
ORDER BY user_id;
